# Node docker image on which this would be run
image: node:14

stages:
  - production
Backend:
  image: ruby:latest
  only:
    - master
  stage: production
  script:
    - cd backend
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
